// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjEsJVb8LnFujYhmgqKpdtKCu3-xCBEs',
    appId: '1:257270517367:web:07720ac9a17cec0bd20072',
    messagingSenderId: '257270517367',
    projectId: 'notificationapp-8de26',
    authDomain: 'notificationapp-8de26.firebaseapp.com',
    storageBucket: 'notificationapp-8de26.firebasestorage.app',
    measurementId: 'G-FBHD1V4TDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKH1P51JICwqEPiFBr-ASqFdluGZmUz4',
    appId: '1:257270517367:android:85bed8fea0adbedad20072',
    messagingSenderId: '257270517367',
    projectId: 'notificationapp-8de26',
    storageBucket: 'notificationapp-8de26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5ZR9ui-wdf31evnpRItqPxKC0pARhIs',
    appId: '1:257270517367:ios:31815ce342f87970d20072',
    messagingSenderId: '257270517367',
    projectId: 'notificationapp-8de26',
    storageBucket: 'notificationapp-8de26.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM5ZR9ui-wdf31evnpRItqPxKC0pARhIs',
    appId: '1:257270517367:ios:31815ce342f87970d20072',
    messagingSenderId: '257270517367',
    projectId: 'notificationapp-8de26',
    storageBucket: 'notificationapp-8de26.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjEsJVb8LnFujYhmgqKpdtKCu3-xCBEs',
    appId: '1:257270517367:web:2abe27c9e5200529d20072',
    messagingSenderId: '257270517367',
    projectId: 'notificationapp-8de26',
    authDomain: 'notificationapp-8de26.firebaseapp.com',
    storageBucket: 'notificationapp-8de26.firebasestorage.app',
    measurementId: 'G-WESK309SL4',
  );
}
